# Lots of the contents were copied from NATHANIEL LANDAU's execllent blog at
# http://natelandau.com/my-mac-osx-bash_profile/

### look & feel ###
export CLICOLOR='true'
export LSCOLORS="gxfxcxdxbxegedabagacad"

#   Change Prompt
#   ------------------------------------------------------------
export PS1="___________________    | \w @ \h (\u) \n| => "
export PS2="| => "

#   Set default blocksize for ls, df, du
#   from this: http://hints.macworld.com/comment.php?mode=view&cid=24491
#   ------------------------------------------------------------
export BLOCKSIZE=1k

# set editor variable for general editing
export EDITOR=vim

### Open Source Dev ###

PATH=/Users/peng/devenv/tools/leiningen/:$PATH
export PATH

#export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

export GRADLE_HOME=/Users/peng/devenv/tools/gradle-2.2.1
export PATH=$GRADLE_HOME/bin:$PATH

export SCALA_HOME=/Users/peng/devenv/tools/scala-2.11.4
export PATH=$SCALA_HOME/bin:$PATH

export ANT_HOME="/Users/peng/devenv/tools/apache-ant-1.9.4"
export PATH=$ANT_HOME/bin:$PATH

# Alias
alias ls='ls -lart'
alias vi='vim'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'

alias flush-dns='sudo killall -HUP mDNSResponder; dscacheutil -flushcache'

alias gradled='gradle --daemon '

#   ---------------------------
#   6.  NETWORKING
#   ---------------------------

alias myip='curl ip.appspot.com'                    # myip:         Public facing IP Address
alias netCons='lsof -i'                             # netCons:      Show all open TCP/IP sockets
alias flushDNS='dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs


### history handling ###
#
# Erase duplicates
export HISTCONTROL=erasedups
# resize history size
export HISTSIZE=5000
# append to bash_history if Terminal.app quits
shopt -s histappend

export PATH="/usr/local/bin:$PATH"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
